spring.application.name=backend

#Mysql 설정
spring.datasource.url=jdbc:mysql://localhost:3306/eatsadeal?createDatabaseIfNotExist=true&useSSL=false&allowPublicKeyRetrieval=true&serverTimezone=Asia/Seoul&characterEncoding=UTF-8
spring.datasource.username=root
spring.datasource.password=1234
spring.datasource.driver-class-name=com.mysql.cj.jdbc.Driver

#jpa 설정
spring.jpa.hibernate.ddl-auto=update
spring.jpa.show-sql=true
spring.jpa.properties.hibernate.format_sql=true
spring.jpa.database-platform=org.hibernate.dialect.MySQLDialect

#jwt 설정
jwt.secret=temp-my-project-jwt-secret-key-must-be-at-least-32-bytes-long
jwt.expiration-ms=21600000

# IntelliJ에서 백엔드 실행 시 프론트엔드 Vite 서버도 함께 실행
frontend.dev-server.enabled=true
